source ~/.dotfiles/zsh/alias.zsh
source ~/.dotfiles/zsh/asdf.zsh
source ~/.dotfiles/zsh/docker.zsh
source ~/.dotfiles/zsh/dotfiles.zsh
source ~/.dotfiles/zsh/git.zsh
source ~/.dotfiles/zsh/gitlab.zsh
source ~/.dotfiles/zsh/java.zsh
source ~/.dotfiles/zsh/kubectl.zsh
source ~/.dotfiles/zsh/proxy.zsh
source ~/.dotfiles/zsh/p10k.zsh
source ~/.dotfiles/zsh/lscolors.zsh